### ISSUE TITLE
[BUG] Currently Reading not populated

### ISSUE THREAD

**Issue by justcallmelarry** [LeoKlaus/plappa#172] opened 2024-08-20 21:39 UTC
**Describe the bug**
When opening the app (or switching to home from anywhere) the currently listening books are not populated (Audiobookshelf v.2.12.3 backend).

**To Reproduce**
1. Go to Home
2. Only "Recently added" is populated, even though I have a book in progress.

**Expected behavior**
Should see the book that is in progress.

**Logs**
[2024-08-20, 23:32] [CoreDataHandler] Initializing core data store...
[2024-08-20, 23:32] [CoreDataHandler] CoreData store initialized
[2024-08-20, 23:32] [PlaybackStateHandler] Syncing playback states through server
[2024-08-20, 23:32] [ReadingListHandler] Found no objects in reading list
[2024-08-20, 23:32] [PlaybackSessionHandler] Syncing playback sessions through server
[2024-08-20, 23:32] [AudioBookShelfAPIHandler] Successfully posted sessions
[2024-08-20, 23:32] [plappa] Encountered an error while decoding sessions: The data couldn’t be read because it is missing.
valueNotFound(Swift.String, Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "sessions", intValue: nil), _JSONKey(stringValue: "Index 389", intValue: 389), CodingKeys(stringValue: "libraryId", intValue: nil)], debugDescription: "Cannot get unkeyed decoding container -- found null value instead", underlyingError: nil))

**Environment(please complete the following information):**
 - Device: iPhone 12 Pro Max
 - OS: iOS 17.5.1
 - Version 1.4.1
 - Server Version Audiobookshelf v.2.12.3

**Comment by LeoKlaus** [comment] 2024-08-24 10:48
Hey Lauri,

thank you for reporting this and including the logs. This is caused by plappa being unable to load your listening progress, I just submitted an update to TestFlight that should fix this issue (1.4.2 build 47). It's currently waiting for review and should release in coming days.

If you're not in the TestFlight beta, you can join here: https://testflight.apple.com/join/oSAekRD5

**Comment by justcallmelarry** [comment] 2024-08-26 14:04
> Hey Lauri,
> 
> thank you for reporting this and including the logs. This is caused by plappa being unable to load your listening progress, I just submitted an update to TestFlight that should fix this issue (1.4.2 build 47). It's currently waiting for review and should release in coming days.
> 
> If you're not in the TestFlight beta, you can join here: https://testflight.apple.com/join/oSAekRD5

Indeed, now it works like it used to! Which leads me to another issue, but I can open a separate ticket for that :D Thanks for the fix!

Edit: this can be closed from my side, but i saw that you re-opened the ticket, so i dont want to close it if you are tracking it somehow

**Comment by LeoKlaus** [comment] 2024-09-21 13:05
The fix is now live on the AppStore as well, so I'll close this.

**Closed as completed by LeoKlaus** 2024-09-21 13:05 UTC
Labels: bug
