### ISSUE TITLE
[BUG] Clicking on specific track starts different track

### ISSUE THREAD

**Issue by wfrank21** [LeoKlaus/plappa#77] opened 2024-04-26 14:22 UTC
**Describe the bug**
Trying to start a specific track within a book starts a completely different track

**To Reproduce**
Click on a Book
Choose a track
Random other track gets played

**Expected behavior**
Playing of selected track starts

**Screenshots**

![IMG_1374](https://github.com/LeoKlaus/plappa/assets/73826476/3bc1946a-d689-4eef-afb2-6f68b894729e)
Tapped on the blue track, different track plays.

**Logs**

Environment(please complete the following information):

Device: iPhone 15
OS: iOS 17.4.1
Version 1.1.3
Server Version Jellyfin 10.8.13

**Comment by LeoKlaus** [comment] 2024-04-26 14:31
I'm pretty sure this is caused by #76 (or the other way around). Do these files appear in the correct order in Jellyfin?

**Comment by wfrank21** [comment] 2024-04-26 14:33
Yeah in the official App and on the web interface they appear in the correct order, sorted by name
![IMG_1377](https://github.com/LeoKlaus/plappa/assets/73826476/d29409ab-cbe7-43b8-a8c9-d5f300da28a5)

**Comment by LeoKlaus** [comment] 2024-04-27 08:00
This is fixed with 1.1.4 build 5.

**Closed as completed by LeoKlaus** 2024-04-27 08:00 UTC
Labels: bug
