### ISSUE TITLE
[FEATURE] Send listening stats from Plappa to ABS

### ISSUE THREAD

**Issue by muppie** [LeoKlaus/plappa#122] opened 2024-06-12 05:13 UTC
Would love to send my listening stats from Plappa to ABS

**Comment by LeoKlaus** [comment] 2024-06-12 12:39
Hey muppie,

thanks for the suggestion! This has definitely been one of the most requested features and I look forward to implement it.
I've laid some important ground work for this (and a listening history within plappa) with the upcoming 1.1.6 update.

This should come with an update in the near future.

**Comment by mindtakerr** [comment] 2024-06-13 20:31
I have a related issue, but I think it might fall under this one. If I continue a book on Audiobookshelf, it does not seem to update my progress in Plappa. Is that part of the same feature?

**Comment by LeoKlaus** [comment] 2024-06-13 20:35
> I have a related issue, but I think it might fall under this one. If I continue a book on Audiobookshelf, it does not seem to update my progress in Plappa. Is that part of the same feature?

No, that should work. Can you check if restarting plappa causes the progress to load correctly? I've created a new issue in #128 to track this.

**Comment by LeoKlaus** [comment] 2024-08-03 16:12
Closing this as it's a duplicate of #83.

**Closed as completed by LeoKlaus** 2024-08-03 16:12 UTC
Labels: bug
