### ISSUE TITLE
[BUG] Playback position not being synced after listening through ABS WebUI

### ISSUE THREAD

**Issue by Drikani** [LeoKlaus/plappa#84] opened 2024-05-01 19:09 UTC
**Describe the bug**
When listening to a audiobook through the WebUI the new playback position is not being updated in Plappa

**To Reproduce**
1. Listen to a Audiobook on ABS
2. Open Plappa and resume the Audiobook there
3. Plappa continues where you last left in Plappa and not where you stopped on ABS

**Expected behavior**
The current progress from ABS should be synced before playback resumes in Plappa.

**Environment(please complete the following information):**
 - Device: iPhone 15 Pro
 - OS: iOS 17.4.1
 - Version 1.1.5
 - Server Version  2.9.0

**Comment by LeoKlaus** [comment] 2024-05-03 07:01
Playback progress is synced whenever plappa is opened (or moved to the foreground). If you didn't close plappa or lock your phone while playing through the web interface, no sync will have happened. The ABS web interface only saves playback every 10-15 seconds, maybe that was the cause?

**Comment by LeoKlaus** [comment] 2024-06-16 09:42
As it's been quiet here for quite some time, I'll close this issue for now. If you encounter this again, feel free to reopen.

**Closed as completed by LeoKlaus** 2024-06-16 09:42 UTC
Labels: bug
