### ISSUE TITLE
[BUG] CarPlay not detecting server

### ISSUE THREAD

**Issue by PleaseStopAsking** [LeoKlaus/plappa#8] opened 2024-02-29 15:06 UTC
**Describe the bug**
When launching plappa via CarPlay, it randomly reports..
```
No server found
Please open plappa on your iPhone
```

When opening the app via iPhone, the CarPlay issue persists. I can still start/stop a book via the phone when this happens however.

Debug logs show no failures or errors.

**To Reproduce**
1. Connect iPhone to CarPlay
2. Launch app via CarPlay

**Expected behavior**
CarPlay shows plappa interface

**Screenshots**
![1868574E-645B-4216-8764-9A33B4B94924_1_102_o](https://github.com/LeoKlaus/plappa/assets/35308946/7cb9bb7b-26ec-41da-8643-e3ccc97ef66d)
![F44278BF-9B8A-4B20-92D9-A9E259F2AA08_1_105_c](https://github.com/LeoKlaus/plappa/assets/35308946/233838c8-e1e8-49f6-a181-6d5b9d75b610)

**Environment(please complete the following information):**
 - Device: `iPhone 14 Pro`
 - OS: `iOS 17.3.1`
 - Version: `TestFlight v0.9`
 - Server Version: `Audiobookshelf v2.8.0`

**Additional context**
I know that CarPlay support is still a WIP but I wanted to log this for knowledge.

**Comment by LeoKlaus** [comment] 2024-03-01 09:16
Hey Micheal,

thanks for reporting this!
My current car doesn't have CarPlay, so I can only test in the CarPlay simulator, which is obviously not a real world test. In the Simulator, it does seem to work reliably, though.

This error is only shown when the ApiHandler cannot be initialized, which should only happen when the credentials are not saved properly. This would also lead to the iPhone app not working, so I guess I'm missing something here.

Did you have plappa open on your iPhone before connecting to your car or did you open it through CarPlay?

**Comment by PleaseStopAsking** [comment] 2024-03-01 14:04
I tested a number of times using the below workflows but could never seem to isolate when it occurs.

- Force close app on phone before connecting to CarPlay and then open via CarPlay
- Force close app on phone before connecting CarPlay and then open via phone followed by CarPlay
- Open app on phone before connecting CarPlay and then open via CarPlay

In all workflows, it appears that the issue is random so far.

**Comment by PleaseStopAsking** [comment] 2024-03-01 19:10
It came up again this afternoon but this time, I was able to see errors in the logs. 

```
[3/1/2024, 7:37 AM] [AudioBookShelfAPIHandler] Tried to init ABS APIHandler with no valid token in keychain
[3/1/2024, 7:37 AM] [PlaybackStateHandler] Couldnt instantiate APIHandler, not pushing updated playbackstates.
```

**Comment by LeoKlaus** [comment] 2024-03-01 19:31
> It came up again this afternoon but this time, I was able to see errors in the logs.

That's interesting, I'll have to look into this. Thanks for the update!

> While these errors are thrown, I can use the app via phone with no issues.

That's just weird. Did you download the audiobooks you were trying to play? If the ApiHandler is not initialized, plappa shouldn't be able to send any requests to your server. I suspect the error only occurred in the CarPlay app.

**Comment by PleaseStopAsking** [comment] 2024-03-01 19:34
>That's just weird. Did you download the audiobooks you were trying to play? If the ApiHandler is not initialized, plappa shouldn't be able to send any requests to your server. I suspect the error only occurred in the CarPlay app.

no, nothing is downloaded.

**Comment by LeoKlaus** [comment] 2024-03-07 15:55
Okay, I've found the issue with this and #1...

plappa uses the on-device keychain to store the token used to authenticate with the server. If the ApiHandler can't obtain that token from keychain, it will fail to initialize.

The reason this happens is that keychain isn't available when the device is locked.

You should be able to reliably reproduce this issue by not looking at your phone before opening plappa via CarPlay. It shouldn't matter whether plappa is open on your device beforehand as the CarPlay delegate spawns its own ApiHandler, which will fail whenever the device is locked (little lock icon above the date on your lockscreen).


I'll have to figure out a way to mitigate this without reducing security significantly (I really don't want to store the login token in UserDefaults...)

**Comment by LeoKlaus** [comment] 2024-03-07 21:56
I've just pubished update 0.9 (build 19). It contains a fix for the ApiHandler failing to initialize while the device is locked in addition to some additional debug info if keychain operations fail.

I'll still leave this open for now but it should be fixed.

**Comment by PleaseStopAsking** [comment] 2024-03-08 18:12
I will test later today and report back.

**Comment by PleaseStopAsking** [comment] 2024-03-19 16:14
After countless uses via CarPlay, I have not seen this issue come up again.

**Comment by LeoKlaus** [comment] 2024-03-19 16:16
> After countless uses via CarPlay, I have not seen this issue come up again.

Great to hear! I'll mark this as closed then. If you have any other feedback, feel free to let me know!

**Closed by LeoKlaus** 2024-03-19 16:16 UTC
Labels: bug
