### ISSUE TITLE
[BUG] Download does not work, zero KB Audiobooks

### ISSUE THREAD

**Issue by mrburns-42** [LeoKlaus/plappa#106] opened 2024-05-20 19:58 UTC
**Describe the bug**
Since Plappa 1.1.6 (3) it is often not possible to download audio books. In the overview of files to be downloaded, only a file size of zero KB is listed and then nothing happens.

Restarting the app usually only helps after a few times. The error then still occurs with other audiobooks.

**To Reproduce**
1. Go to an audiobook.
2. Click on Download.
3. Click again on Download to open the overview of the downloads.
4. See error.

**Expected behavior**
That the audio book is downloaded.

**Screenshots**
![Bildschirmfoto 2024-05-20 um 21 38 22](https://github.com/LeoKlaus/plappa/assets/786982/d45a939a-2737-4813-bdf0-eed30b8b2011)

**Environment(please complete the following information):**
 - Device: iPhone 15 Pro / iPad Pro (11 Zoll)
 - OS: iOS 17.4.1 / iPadOS 17.4.1
 - Version 1.1.6 (3)
 - Server Version ABS 2.9.0

**Comment by LeoKlaus** [comment] 2024-05-22 08:27
Whoops, didn't mean to close this already.

This was the issue that lead me to disable background downloads at first (causing #42).

When implementing background downloads, I followed the Apple guidelines which state that large (background) downloads should be discretionary.
That means that the OS is in charge of starting the download, often delaying it until the device is connected to wifi or a charger. This is obviously not the intended behavior in this case.

I've just released build 4 of 1.1.6 that should fix this issue (and adds a (preliminary) German translation).

**Comment by karimadolfo** [comment] 2024-05-23 13:13
This issue is also present in version 1.1.5 (latest available for me in iOS App Store). I just purchased today and noticed it.

**Comment by LeoKlaus** [comment] 2024-05-23 13:26
> This issue is also present in version 1.1.5 (latest available for me in iOS App Store). I just purchased today and noticed it.

Thank you for your support and for reaching out!
This has to be another issue, this one was only introduced with the 1.1.6 update.

Can you [open another issue](https://github.com/LeoKlaus/plappa/issues/new?assignees=LeoKlaus&labels=bug&projects=&template=bug_report.md&title=%5BBUG%5D+) and add some information on your setup? Specifically:
- What server software are you using? (Emby, Jellyfin or Audiobookshelf)
- Does this happen to all audiobooks or just a few?
- Can you reliably reproduce this?
- Is there anything in the plappa logs? (at the very bottom of the settings tab)

**Comment by karimadolfo** [comment] 2024-05-28 09:49
Hi @LeoKlaus  you were right. Logging out and logging in to my server solved the issue, thank you and sorry for creating noise here.

**Comment by LeoKlaus** [comment] 2024-07-31 15:51
This should be fixed with the latest release of 1.4.0. If the issue reappears, please reopen this.

**Closed as completed by LeoKlaus** 2024-07-31 15:51 UTC
Labels: bug
