### ISSUE TITLE
[BUG] Progress not displayed in audiobookshelf (but is synced)

### ISSUE THREAD

**Issue by justcallmelarry** [LeoKlaus/plappa#188] opened 2024-09-11 14:16 UTC
**Describe the bug**
When listening to downloaded books in plappa, no UI representation of the progress is updated in my web app.

If I press play in the web app, it seems to pick up at the correct place.

If I press play in the first party app, it does not pick up from the correct place.

**To Reproduce**
1. Download a book in plappa
2. Listen to it for a while (with access to the server the whole time)
3. Go to your audiobookshelf web ui
4. No progress bar is apparent, nor is the progress "box" on the item page

**Expected behavior**
The synced progress should be visible in the web app.

**Screenshots**
<img width="226" alt="image" src="https://github.com/user-attachments/assets/0fa200b6-100c-458d-ab4d-99092f4f4b26">

**Environment(please complete the following information):**
 - Device: iPhone 12 Pro Max
 - OS: iOS 17.6.1
 - Version 1.4.3 (52) _on testflight_
 - Server Version ABS 12.3.4

**Additional context**
My guess as to why this happens is that "progress" get's reported twice for the same item every time an update is made (for at least downloaded items). here are some curated logs from my reverse proxy:
```
┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Timestamp           ┃ Request                             ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ 2024-09-11T15:54:34 │ POST /api/authorize                 │
│ 2024-09-11T15:54:34 │ POST /api/session/local             │
│ 2024-09-11T15:54:34 │ PATCH /api/me/progress/batch/update │
│ 2024-09-11T15:54:43 │ POST /api/authorize                 │
│ 2024-09-11T15:54:43 │ POST /api/session/local             │
│ 2024-09-11T15:54:43 │ PATCH /api/me/progress/batch/update │
│ 2024-09-11T15:54:51 │ POST /api/authorize                 │
│ 2024-09-11T15:54:51 │ POST /api/session/local             │
│ 2024-09-11T15:54:51 │ PATCH /api/me/progress/batch/update │
└─────────────────────┴─────────────────────────────────────┘
```

And here are the logs from ABS:
```
2024-09-11 15:42:01.457 DEBUG [PlaybackSessionManager] Updated session for "Task Force Hammer" (A4526804-24CF-420F-8446-6CE7A08B8380)

2024-09-11 15:42:01.467 DEBUG [PlaybackSessionManager] Updating progress for "Task Force Hammer" with current time 22120.001953125 (previously 22110.001509852)
```

So it looks like the session first updates the listening progress, but then a progress update _also_ happens (`/api/me/progress/batch/update`) which confuses the server.

When checking my reverse proxy logs using the first party app the calls look like this instead:
```
┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Timestamp           ┃ Request                 ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ 2024-09-11T16:11:41 │ POST /api/session/local │
│ 2024-09-11T16:12:01 │ POST /api/session/local │
│ 2024-09-11T16:12:26 │ POST /api/session/local │
│ 2024-09-11T16:12:51 │ POST /api/session/local │
│ 2024-09-11T16:13:16 │ POST /api/session/local │
│ 2024-09-11T16:13:41 │ POST /api/session/local │
│ 2024-09-11T16:14:06 │ POST /api/session/local │
└─────────────────────┴─────────────────────────┘
```

This updates the progress correctly for both the web ui and the apps (including plappa),

**Comment by justcallmelarry** [comment] 2024-09-12 15:59
Been trying to follow up research this a bit. I added a 204 response (with an empty body) in my `Caddyfile`,  which I hoped would solve this issue for me. But it persists. So most of my guesses are probably incorrect.

**Comment by LeoKlaus** [comment] 2024-09-12 17:16
Thank you for the update. This is probably caused by plappa not transmitting the duration with the mediaprogress. ABS used to handle this just fine, but it started causing some issues around the 2.13.2 update (mainly #183).

I already added the duration field, but can't upload the update to TestFlight right now as AppStore Connect is down...

I'll post an update once it's ready to test :)

**Comment by LeoKlaus** [comment] 2024-09-12 17:16
Oh, the separate sync of the progress will be removed soon, it's simply not needed now that sessions are synced.

**Comment by justcallmelarry** [comment] 2024-09-12 17:30
> Oh, the separate sync of the progress will be removed soon, it's simply not needed now that sessions are synced.

At least if you have your abs backend up to date! 😅

> Thank you for the update. This is probably caused by plappa not transmitting the duration with the mediaprogress. ABS used to handle this just fine, but it started causing some issues around the 2.13.2 update (mainly #183).
> 
> I already added the duration field, but can't upload the update to TestFlight right now as AppStore Connect is down...
> 
> I'll post an update once it's ready to test :)

I have an ABS debugging setup on my server, so I tried monkeypatching the requests with the duration field, and it indeed works as expected after adding it to the request body after force-quitting the app to ensure a new session was created)!

I also found that the `progress` value for the mediaItem (from the authorize endpoint) was set to 0, so I was trying to find where it's calculated, but it never crossed my mind that it might take the duration key from the actual request, not from the database or similar… Nice catch!

**Comment by LeoKlaus** [comment] 2024-09-12 18:37
> I also found that the `progress` value for the mediaItem (from the authorize endpoint) was set to 0, so I was trying to find where it's calculated, but it never crossed my mind that it might take the duration key from the actual request, not from the database or similar… Nice catch!

It's a weird design choice. Having progress, current time and duration in the mediaprogress itself is already redundant, and the duration is also stored in the media item.

**Comment by justcallmelarry** [comment] 2024-09-12 20:03
> > I also found that the `progress` value for the mediaItem (from the authorize endpoint) was set to 0, so I was trying to find where it's calculated, but it never crossed my mind that it might take the duration key from the actual request, not from the database or similar… Nice catch!
> 
> It's a weird design choice. Having progress, current time and duration in the mediaprogress itself is already redundant, and the duration is also stored in the media item.

I opened a [PR for audiobookshelf](https://github.com/advplyr/audiobookshelf/pull/3411) to also fix this issue (I know you have a fix also, but never hurts to plug all holes) at the root, so hopefully it gets accepted. I noticed that it is already using the `libraryItem.duration` for all non-local sessions, so this should mainly be a fix to make them work more similarly.


EDIT: PR was merged :) so hopefully this also helps people on older versions of the app (assuming they update the server)

**Comment by LeoKlaus** [comment] 2024-09-13 09:53
Great work, thank you!
I've just released build 53 of plappa to TestFlight that also adds the duration field to all progress updates, so this should definitely be fixed now ;)

**Closed as completed by LeoKlaus** 2024-09-13 09:53 UTC
Labels: bug
