### ISSUE TITLE
[BUG] Single-Episode Podcasts with frequent replacing updates fill up recently added section

### ISSUE THREAD

**Issue by jannickfahlbusch** [LeoKlaus/plappa#207] opened 2024-10-24 10:13 UTC
**Describe the bug**

The [tagesschau in 100 Sekunden](https://www.tagesschau.de/multimedia/sendung/tagesschau_in_100_sekunden/audio-201734.html) podcast has only a single episode which is being replaced every few hours with a new one for the most recent news.

Each time a new episode is added this new one turns up in the recently added section while the old one remains in the section as well. 
Over time this accumulates many episodes which are not even existent anymore as they have been replaced with a newer one.

**To Reproduce**
1. Subscribe to tagesschau in 100 Sekunden
2. Wait a few hours to have a few replaced episodes
3. Go to "Recently Added"
4. See multiple episodes of the podcast

**Expected behavior**

Only a single episode should be shown as there are not multiple ones.

**Screenshots**
![645ED6C8-B971-479C-BCCD-450D88953F1E_1_201_a](https://github.com/user-attachments/assets/616cf8e6-b70a-42bd-9fb5-6daa68870a3d)

**Logs**

The issue should be easily reproduceable, I can add logs in case they are needed.

**Environment(please complete the following information):**
 - Device: iPhone 14 Pro
 - OS: 18.0.1
 - Version: 1.4.3
 - Server Version: ABS 2.15.1
 

**Additional context**

Thank you very much for the awesome app!

**Comment by LeoKlaus** [comment] 2024-10-28 09:07
Thank you for reporting this. Usually, plappa would recognize deleted items and remove them locally as well. I just added the podcast on my server and will check why that fails.

**Comment by LeoKlaus** [comment] 2024-11-09 17:53
I finally got around to this. The issue is that ABS doesn't replace the episodes either and plappa can only work with the metadata it gets from there.

As this isn't a bug in plappa, I'm closing this for now. You might have luck opening a bug report for ABS itself, but I'm assuming they won't consider a bug either, as this is not how podcasts usually work.

**Closed as completed by LeoKlaus** 2024-11-09 17:53 UTC
Labels: bug
