### ISSUE TITLE
[BUG] Login fails after media playback, resulting in error while decoding auth response

### ISSUE THREAD

**Issue by stanislavhutter** [LeoKlaus/plappa#183] opened 2024-09-05 12:07 UTC
**Describe the bug**
Login with a new user works. But a playback/stop renders a additional login attempt as non functional. The App does not show any information, debug logs hints to a null present, but a int is expected.

The playback/stop creates a null in a mediaProgress entry named duration. 

I used the following to identify the Problem:

`curl --request POST \
  --url https://abs.yourdomain.com/login \
  --header 'Content-Type: application/json' \
  --data '{
	"username": "demo",
	"password": "demopass"
}'`

While Playing:

`
"mediaProgress" : [
         {
            "currentTime" : 3.22683167457581,
            "duration" : 0,
            "ebookLocation" : null,
            "ebookProgress" : 0,
            "episodeId" : null,
            "finishedAt" : null,
            "hideFromContinueListening" : false,
            "id" : "8125b54f-2af8-4b4e-90af-420ce3d46e42",
            "isFinished" : false,
            "lastUpdate" : 1725534521557,
            "libraryItemId" : "8577d699-679e-47d6-8bfc-93227d8e8ebc",
            "mediaItemId" : "cc95ed03-0bcd-4aaa-adf3-0d9b3b99869f",
            "mediaItemType" : "book",
            "progress" : 0,
            "startedAt" : 1725534521557,
            "userId" : "d15a57c8-e0df-4ceb-a595-4d34ec865660"
         }
      ],
`

After Stopping:

`
"mediaProgress" : [
         {
            "currentTime" : 3.22792434692383,
            "duration" : null,
            "ebookLocation" : null,
            "ebookProgress" : 0,
            "episodeId" : null,
            "finishedAt" : null,
            "hideFromContinueListening" : false,
            "id" : "d2b4e7ca-a65a-459c-9d90-5e211ec8b7a6",
            "isFinished" : false,
            "lastUpdate" : 1725534521644,
            "libraryItemId" : "8577d699-679e-47d6-8bfc-93227d8e8ebc",
            "mediaItemId" : "cc95ed03-0bcd-4aaa-adf3-0d9b3b99869f",
            "mediaItemType" : "book",
            "progress" : 0,
            "startedAt" : 1725534521554,
            "userId" : "d15a57c8-e0df-4ceb-a595-4d34ec865660"
         }
      ],
`

**To Reproduce**
1. Create a new user in ABS
2. Login as the new user
3. Start the playback of a audiobook and stop it
4. Logout
5. Login -> does not work.

**Expected behavior**
The login should work. But it does not. 

**Logs**
`
[5.9.2024, 13:18] [plappa] Encountered an error while decoding auth response: The data couldn’t be read because it is missing.
valueNotFound(Swift.Float, Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "user", intValue: nil), CodingKeys(stringValue: "mediaProgress", intValue: nil), _JSONKey(stringValue: "Index 1", intValue: 1), CodingKeys(stringValue: "duration", intValue: nil)], debugDescription: "Cannot get unkeyed decoding container -- found null value instead", underlyingError: nil))
`

**Environment(please complete the following information):**
 - Device: Iphone 13 mini, Ipad Air m1
 - OS: iOS 17.6.1, ipadOS 17.6.1
 - Version: latest from appstore
 - Server Version:  ABS 2.13.3

**Comment by HudsonHawk** [comment] 2024-09-05 17:36
I am having the same issue. I can log in via the Web UI and the AudioBookshelf beta app, but not with Plappa.

**Comment by LeoKlaus** [comment] 2024-09-05 17:41
Thank you both for reporting this. You're actually experiencing the same issue that's already discussed in #182, so I'll close this.

This issue is already closed in the latest TestFlight release, the AppStore version is waiting for review.

**Comment by LeoKlaus** [comment] 2024-09-05 19:32
Quick update: update 1.4.2 is now live in the AppStore as well, if you still encounter this issue after updating, please reopen this or add a comment to #182.

**Closed as completed** 2024-09-05 19:32 UTC
Labels: bug

**Comment by rasmuslos** [comment] 2024-09-10 16:39
This actually broke ShelfPlayer too, please be more careful next time and consider fixing broken MediaProgress entities rather then just updating plappa to handle them. Malformed entities can break all other statically typed clients.

I wasted more than two hours in total on this, most of it trying to find the cause...

**Comment by rasmuslos** [comment] 2024-09-10 16:50
And please conform to the [API-docs](https://api.audiobookshelf.org/#media-progress). plappa still sets the duration property to `null`, even though the API spec does not allow it, again, breaking compatibility with other statically typed clients.

**Comment by LeoKlaus** [comment] 2024-09-10 17:14
> This actually broke ShelfPlayer too, please be more careful next time and consider fixing broken MediaProgress entities rather then just updating plappa to handle them. Malformed entities can break all other statically typed clients.
> 
> I wasted more than two hours in total on this, most of it trying to find the cause...

Hi Rasmus, I understand your frustration, but this one is not (only) on me. The docs [specifically mention a default for duration](https://api.audiobookshelf.org/#batch-create-update-media-progress) and ABS just stopped setting that for whatever reason with 2.13.2 or 2.13.3. Plappa doesn't submit any value for duration when updating playback states and it will never specifically set anything to null.

I've run into a ton of issues like that, the API docs for ABS simply treat a lot of values as non-optional that can and will 
be null at times even without the use of third party clients.


Also, please mind your tone when commenting, especially considering you broke third party clients by (actually) not adhering to the api docs yourself just two months ago (see #137 / rasmuslos/ShelfPlayer#115).


PS: It's great to see others putting time and effort into iOS apps for self hosted tools and I really appreciate your work.

**Comment by rasmuslos** [comment] 2024-09-10 17:22
I agree with you, the validation in ABS could be better, and I apologize for braking bookmarks. I was really annoyed because of this, mostly because I wasted so much time that I would have liked to spend some other way. But it's true, "Wer im Glashaus sitzt, sollte nicht mit Steinen schmeißen", and I apologize for my language.

And thanks, I appreciate plappa, too :)

**Comment by LeoKlaus** [comment] 2024-09-10 17:25
Thank you for keeping it friendly. I absolutely understand your frustration and I've since fixed this issue, but it'll probably take a week or so before the update goes live on the AppStore.

Sorry for the troubles :)

**Comment by rasmuslos** [comment] 2024-09-10 17:30
I uploaded a fix to the AppStore which should go live soon, so not worries!
